Fix rendering failures caused by not clearing the current context.
NatronGitHub/Natron pull request #871
Opened 2023-04-21 15:35 UTC by acolwell

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Additionally, make sure you've done all of these things:

- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CODE_OF_CONDUCT.md) to the best of my understanding
- [x] I've read and understood the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md)
- [x] I've formatted my code according to Natron's [code style]([#](https://github.com/NatronGitHub/Natron#logistics))
- [x] I've searched the [pull requests tracker](https://github.com/NatronGitHub/Natron/pulls?q=is%3Apr) to ensure that this PR is not a duplicate

## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality nor fixes a bug but improves Natron in some way)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
    - [ ] I have updated the documentation accordingly

**What does this pull request do?**

This patch fixes 2 bugs where code was leaving a GL context current when it shouldn't have. This was causing rendering failures because code would later try to use a context that was current on one thread to do rendering on another.

This patch contains the following changes:
- Fix GPUContextPool to unset the current context after it has fetched the max texture size.
- Fix OSGLContext_win so it unsets the current context before it returns from analyzeContextWGL().
- Add context clearing in OSGLContext_win for a few exception cases and updated makeContextCurrent(0) to makeContextCurrent(nullptr) for consistency and to make it clear this method takes a pointer.
- Added a unit test that verifies the GPUContextPool and OSGLContext_win::analyzeContextWGL() fixes.

**Have you tested your changes (if applicable)? If so, how?**

Yes. I've verified that this fixes "random" rendering failures I was seeing on Windows. I also created a unit test that verifies the fixes and run them on Windows and Linux. I don't have a Mac dev environment to test with, but the test should detect the same bugs on that platform. I verified the new tests fail without the fixes and pass with them.

2023-04-21 22:22 UTC, devernay requested changes
Thank you for that great contibution!
I suggest changes to the tests so that they can be skipped if no OpenGL renderer is available

2023-04-21 22:22 UTC, devernay commented on Tests/OSGLContext_Test.cpp
> +
suggested, to be able to run test if no DISPLAY is available:
```
if (rendererID.renderID < 0) {
  GTEST_SKIP();
}
```

2023-04-21 22:22 UTC, devernay commented on Tests/OSGLContext_Test.cpp
> +
what happens if !settings?

2023-04-21 22:22 UTC, devernay commented on Tests/OSGLContext_Test.cpp
> +    // Verify that we start without a context being set.
suggested, to be able to run test if no DISPLAY is available:
```
GLRendererID rendererID;
if (settings) {
        rendererID = settings->getActiveOpenGLRendererID();
}
if (rendererID.renderID < 0) {
  GTEST_SKIP();
}
```

2023-04-22 04:05 UTC, acolwell commented on Tests/OSGLContext_Test.cpp
> +
So.. it looks like your gtest fork is quite old and so GTEST_SKIP() does not exist. I tried to do something roughly equivalent for now, but it would probably be good to unfork and use a more current release.

It turns out isOpenGLLoaded() returns false if there isn't a display so I made the test skip based on that for now. If we start being able to load GL w/o a screen then we might have to revisit this.

I also made the test fail if we don't have settings since we need them to get the rendererID to create the pool.

2023-04-22 04:05 UTC, acolwell commented on Tests/OSGLContext_Test.cpp
> +    // Verify that we start without a context being set.
Skip on failed GL loading like above. We don't need the rendererID in this test so I just avoided adding that logic for now.

2023-04-22 18:48 UTC, devernay commented on Tests/OSGLContext_Test.cpp
> +
thank you! of course we can update gtest in a later PR

2023-04-22 18:49 UTC, devernay approved these changes

2023-04-22 18:51 UTC, merged

2023-04-26 06:55 UTC, rodlie commented
This pull breaks X11.

* threadHasACurrentContext returns false (https://github.com/NatronGitHub/Natron/blob/RB-2.5/Engine/OSGLContext.cpp#L306) - don't know (start Natron => add blur => fail)
* Missing ``ifdef __NATRON_WAYLAND__`` (https://github.com/NatronGitHub/Natron/blob/RB-2.5/Engine/OSGLContext.cpp#L426) - trivial fix

2023-04-26 14:21 UTC, acolwell commented
> This pull breaks X11.
> 
> * threadHasACurrentContext returns false (https://github.com/NatronGitHub/Natron/blob/RB-2.5/Engine/OSGLContext.cpp#L306) - don't know (start Natron => add blur => fail)
> * Missing `ifdef __NATRON_WAYLAND__` (https://github.com/NatronGitHub/Natron/blob/RB-2.5/Engine/OSGLContext.cpp#L426) - trivial fix

Sorry about this. I'll try to look into this today. I figured the assert might smoke out other issues.

2023-04-26 14:25 UTC, rodlie commented
No problem or rush :+1: